.gitignore
Dockerfile
nodebb-theme-fdk/README.md
nodebb-theme-fdk/commitlint.config.js
nodebb-theme-fdk/less/categories.less
nodebb-theme-fdk/less/colours.less
nodebb-theme-fdk/less/fdk.less
nodebb-theme-fdk/less/navbar.less
nodebb-theme-fdk/less/text.less
nodebb-theme-fdk/lib/theme.js
nodebb-theme-fdk/package-lock.json
nodebb-theme-fdk/package.json
nodebb-theme-fdk/plugin.json
nodebb-theme-fdk/theme.json
nodebb-theme-fdk/theme.less

feat: adds FDK colours and fonts

---

nodebb-theme-fdk/less/buttons.less
nodebb-theme-fdk/less/fdk.less
nodebb-theme-fdk/less/posts.less

feat: adds fdk thread-styling

---

nodebb-plugin-fdk-sso/library.js

feat: update profile and set fullname

---

nodebb-plugin-fdk-sso/library.js

feat: map access token authorities to roles

---

nodebb-theme-fdk/lib/client.js
nodebb-theme-fdk/templates/fdk-header.tpl

fix: adapt home link to env

---

nodebb-theme-fdk/less/fdk.less
nodebb-theme-fdk/less/user.less
nodebb-theme-fdk/templates/account/profile.tpl
nodebb-theme-fdk/templates/partials/account/header.tpl

feat: adds styling to user account page

---

nodebb-theme-fdk/less/user.less
nodebb-theme-fdk/templates/account/edit.tpl
nodebb-theme-fdk/templates/account/settings.tpl

fix: fixes user edit and settings layout

---

nodebb-theme-fdk/languages/en-GB/fdk.json
nodebb-theme-fdk/languages/en-US/fdk.json
nodebb-theme-fdk/languages/nb/fdk.json
nodebb-theme-fdk/plugin.json
nodebb-theme-fdk/templates/fdk-footer.tpl
nodebb-theme-fdk/templates/fdk-header.tpl
nodebb-theme-fdk/templates/header.tpl

Ikke all tekst er oversatt her - i første omgang kun det jeg kom over ved surfing på de forskjellige community sidene. Mer kan oversettes ved behov tenker jeg.
Closes #23

feat: adds custom localization

---

nodebb-theme-fdk/less/fdk.less
nodebb-theme-fdk/less/groups.less
nodebb-theme-fdk/templates/groups/details.tpl

fix: groups page styling

---

Dockerfile

chore: nodebb upgrade to 1.17.x

---

nodebb-theme-fdk/languages/en-GB/fdk.json
nodebb-theme-fdk/languages/en-US/fdk.json
nodebb-theme-fdk/languages/nb/fdk.json
nodebb-theme-fdk/templates/account/edit.tpl

Closes Informasjonsforvaltning/fdk-issue-tracker#280

feat: restricts user editing

---

nodebb-theme-fdk/templates/partials/menu.tpl

feat: adds text under notification icon

---

nodebb-theme-fdk/less/category.less
nodebb-theme-fdk/less/posts.less

fix: fixes highlighting styling bug

---

nodebb-plugin-fdk-sso/library.js

feat: handle duplicate username

---

nodebb-theme-fdk/templates/partials/menu.tpl

feat: added consent to menu

---

nodebb-theme-fdk/languages/en-GB/fdk.json
nodebb-theme-fdk/languages/en-US/fdk.json
nodebb-theme-fdk/languages/nb/fdk.json
nodebb-theme-fdk/less/fdk.less
nodebb-theme-fdk/less/registration.less
nodebb-theme-fdk/templates/registerComplete.tpl

fix: fixes consent page

---

Dockerfile
detail.js

Closes #78 
Temporary fix until https://github.com/NodeBB/NodeBB/pull/9581 is merged.

fix: enable editing and deletion of notes, updates template

---

nodebb-theme-fdk/less/category.less

feat: hides deleted posts

---

nodebb-theme-fdk/less/category.less
nodebb-theme-fdk/templates/partials/topics_list.tpl

feat: displays deleted posts for admins and mods

---

nodebb-theme-fdk/less/badge.less
nodebb-theme-fdk/less/fdk.less
nodebb-theme-fdk/templates/account/edit.tpl
nodebb-theme-fdk/templates/partials/topic/badge.tpl

fix: adds option to add group tags

---

nodebb-theme-fdk/templates/fdk-footer.tpl

fix: adds mailto: link

---

nodebb-theme-fdk/lib/client.js
nodebb-theme-fdk/templates/header.tpl
nodebb-theme-fdk/templates/registerComplete.tpl

fix: logout on registration abort

---

Dockerfile.prod

Installs consent plugin for prod

fix: adds consent plugin install to prod dockerfile

---

nodebb-theme-fdk/languages/en-GB/fdk.json
nodebb-theme-fdk/languages/en-US/fdk.json
nodebb-theme-fdk/languages/nb/fdk.json

Fixes: https://github.com/Informasjonsforvaltning/fdk-community-service/issues/135

chore: update welcome text

---

nodebb-theme-fdk/templates/partials/gdpr_consent.tpl

chore: move all checkboxes to bottom of page

---

nodebb-theme-fdk/templates/partials/menu.tpl

Closes datadeling/behov-issue-tracker/issues/134

feat: enable search for logged out users

---

nodebb-plugin-fdk-sso/library.js

Fixes Informasjonsforvaltning/fdk-issue-tracker#505

fix: check if user with email exists before create

---

nodebb-theme-fdk/less/posts.less

fix: wrap post titles

---

Dockerfile
nodebb-theme-fdk/templates/partials/menu.tpl
prod.Dockerfile

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/634

fix: add missing form action

---

.dockerignore
Dockerfile
prod.Dockerfile

chore: upgrade nodebb to 2.5.7

---

Dockerfile
e2e/package-lock.json
e2e/package.json
prod.Dockerfile

chore: upgrade nodebb to 2.8.2 and bump e2e deps

---

nodebb-theme-fdk/less/posts.less

fix: remove word-break: break-all

---

Dockerfile
nodebb-theme-fdk/templates/header.tpl
prod.Dockerfile

chore: add siteimprove tracking code + bump nodebb

---

Dockerfile
e2e/package-lock.json
e2e/package.json
prod.Dockerfile

Fixes https://github.com/Informasjonsforvaltning/fdk-community-service/issues/195

chore: nodebb v2.8.16 upgrade

---

Dockerfile
e2e/cypress.config.js
nodebb-theme-fdk/templates/header.tpl

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/863

fix: add missing monsido settings

---

mail-template-delete-7days.html
mail-template-deleted.html
run.sh
startup.prod.sh
startup.sh

https://docs.nodebb.org/api/write/#tag/users/paths/~1users~1%7Buid%7D~1content/delete

fix: delete user and preserve content

---

run.sh

chore: debug

---

nodebb-theme-fdk/languages/en-GB/fdk.json
nodebb-theme-fdk/languages/en-US/fdk.json
nodebb-theme-fdk/languages/nb/fdk.json
nodebb-theme-fdk/templates/fdk-footer.tpl

relates to https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/914

fix: remove link to datafabrikken in footer

---

Dockerfile
prod.Dockerfile

Fixes https://github.com/Informasjonsforvaltning/fdk-community-service/issues/211

chore: remove ga plugin
